import comp from "D:/projectsvuepress-theme-hope/my-docs/src/.vuepress/.temp/pages/basic_knowledge/smart/DE/de.html.vue"
const data = JSON.parse("{\"path\":\"/basic_knowledge/smart/DE/de.html\",\"title\":\"智能算法整理\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"智能算法整理\",\"icon\":\"linter\",\"category\":[\"目录\",\"导航\"],\"tag\":[\"目录\",\"导航\"],\"sticky\":false,\"star\":false,\"article\":false,\"timeline\":false,\"description\":\"差分进化算法（Differential Evolution，DE）概述 Storn等人1995年提出 通过群体内间的而产生的智能优化搜索 保留了搜索策略。 ps.来自师姐的解释： 降低了进化计算的复杂性 采用实数编码 基于差分的简单变异操作 “一对一”的竞争生存策略 拥有记忆能力 理论基础 算法原理 随机的启发式搜索算法。从数学角度，是一种随机搜索；从...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/singingbird-svg/Note/basic_knowledge/smart/DE/de.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"文档演示\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"智能算法整理\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"差分进化算法（Differential Evolution，DE）概述 Storn等人1995年提出 通过群体内间的而产生的智能优化搜索 保留了搜索策略。 ps.来自师姐的解释： 降低了进化计算的复杂性 采用实数编码 基于差分的简单变异操作 “一对一”的竞争生存策略 拥有记忆能力 理论基础 算法原理 随机的启发式搜索算法。从数学角度，是一种随机搜索；从...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"singingbird\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"目录\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"导航\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"智能算法整理\\\",\\\"description\\\":\\\"差分进化算法（Differential Evolution，DE）概述 Storn等人1995年提出 通过群体内间的而产生的智能优化搜索 保留了搜索策略。 ps.来自师姐的解释： 降低了进化计算的复杂性 采用实数编码 基于差分的简单变异操作 “一对一”的竞争生存策略 拥有记忆能力 理论基础 算法原理 随机的启发式搜索算法。从数学角度，是一种随机搜索；从...\\\"}\"]]},\"headers\":[{\"level\":2,\"title\":\"差分进化算法（Differential Evolution，DE）概述\",\"slug\":\"差分进化算法-differential-evolution-de-概述\",\"link\":\"#差分进化算法-differential-evolution-de-概述\",\"children\":[]},{\"level\":2,\"title\":\"理论基础\",\"slug\":\"理论基础\",\"link\":\"#理论基础\",\"children\":[{\"level\":3,\"title\":\"算法原理\",\"slug\":\"算法原理\",\"link\":\"#算法原理\",\"children\":[]}]},{\"level\":2,\"title\":\"差分进化算法特点\",\"slug\":\"差分进化算法特点\",\"link\":\"#差分进化算法特点\",\"children\":[]},{\"level\":2,\"title\":\"差分进化算法主要参数\",\"slug\":\"差分进化算法主要参数\",\"link\":\"#差分进化算法主要参数\",\"children\":[]},{\"level\":2,\"title\":\"差分进化算法运算流程\",\"slug\":\"差分进化算法运算流程\",\"link\":\"#差分进化算法运算流程\",\"children\":[{\"level\":3,\"title\":\"基本差分进化算法\",\"slug\":\"基本差分进化算法\",\"link\":\"#基本差分进化算法\",\"children\":[]},{\"level\":3,\"title\":\"自适应差分进化算法\",\"slug\":\"自适应差分进化算法\",\"link\":\"#自适应差分进化算法\",\"children\":[]},{\"level\":3,\"title\":\"离散差分进化算法\",\"slug\":\"离散差分进化算法\",\"link\":\"#离散差分进化算法\",\"children\":[]},{\"level\":3,\"title\":\"其他差分进化算法形式\",\"slug\":\"其他差分进化算法形式\",\"link\":\"#其他差分进化算法形式\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.87,\"words\":1462},\"filePathRelative\":\"basic_knowledge/smart/DE/de.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
