import comp from "D:/projectsvuepress-theme-hope/my-docs/src/.vuepress/.temp/pages/others/websafe/info_collect/info.html.vue"
const data = JSON.parse("{\"path\":\"/others/websafe/info_collect/info.html\",\"title\":\"信息收集\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"信息收集\",\"icon\":\"linter\",\"category\":[\"目录\",\"导航\"],\"tag\":[\"目录\",\"导航\"],\"sticky\":false,\"star\":false,\"article\":false,\"timeline\":false,\"description\":\"信息收集包含内容 域名信息、IP段、开放的端口、网站架构、软件版本、WAF、旁站、文件目录架构、C段... 域名信息 域名是什么 Domain name eg. IP地址为192.168.1.110，难以记忆，因此用域名来代替。如baidu.com用来代替IP 域名的分类 国际域名 国别域名 新顶级域名 biz, info, name, pro,aer...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/singingbird-svg/Note/others/websafe/info_collect/info.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"文档演示\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"信息收集\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"信息收集包含内容 域名信息、IP段、开放的端口、网站架构、软件版本、WAF、旁站、文件目录架构、C段... 域名信息 域名是什么 Domain name eg. IP地址为192.168.1.110，难以记忆，因此用域名来代替。如baidu.com用来代替IP 域名的分类 国际域名 国别域名 新顶级域名 biz, info, name, pro,aer...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://img-blog.csdnimg.cn/direct/2e041629e90340f88aabc7ec59e11276.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"singingbird\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"目录\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"导航\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"信息收集\\\",\\\"description\\\":\\\"信息收集包含内容 域名信息、IP段、开放的端口、网站架构、软件版本、WAF、旁站、文件目录架构、C段... 域名信息 域名是什么 Domain name eg. IP地址为192.168.1.110，难以记忆，因此用域名来代替。如baidu.com用来代替IP 域名的分类 国际域名 国别域名 新顶级域名 biz, info, name, pro,aer...\\\"}\"]]},\"headers\":[{\"level\":2,\"title\":\"信息收集包含内容\",\"slug\":\"信息收集包含内容\",\"link\":\"#信息收集包含内容\",\"children\":[]},{\"level\":2,\"title\":\"域名信息\",\"slug\":\"域名信息\",\"link\":\"#域名信息\",\"children\":[{\"level\":3,\"title\":\"域名是什么\",\"slug\":\"域名是什么\",\"link\":\"#域名是什么\",\"children\":[]},{\"level\":3,\"title\":\"域名的分类\",\"slug\":\"域名的分类\",\"link\":\"#域名的分类\",\"children\":[]},{\"level\":3,\"title\":\"域名与IP\",\"slug\":\"域名与ip\",\"link\":\"#域名与ip\",\"children\":[]},{\"level\":3,\"title\":\"查询域名\",\"slug\":\"查询域名\",\"link\":\"#查询域名\",\"children\":[]},{\"level\":3,\"title\":\"子域名\",\"slug\":\"子域名\",\"link\":\"#子域名\",\"children\":[]},{\"level\":3,\"title\":\"域名解析信息\",\"slug\":\"域名解析信息\",\"link\":\"#域名解析信息\",\"children\":[]}]},{\"level\":2,\"title\":\"IP信息获得\",\"slug\":\"ip信息获得\",\"link\":\"#ip信息获得\",\"children\":[{\"level\":3,\"title\":\"DNS服务器的类型\",\"slug\":\"dns服务器的类型\",\"link\":\"#dns服务器的类型\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.03,\"words\":610},\"filePathRelative\":\"others/websafe/info_collect/info.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
