<template><div><h2 id="概念" tabindex="-1"><a class="header-anchor" href="#概念"><span>概念</span></a></h2>
<p>不提前知道工作的数量和加工时间(运行时有新任务加入)</p>
<h2 id="theorem-3-7-1" tabindex="-1"><a class="header-anchor" href="#theorem-3-7-1"><span>Theorem 3.7.1</span></a></h2>
<h3 id="相关概念" tabindex="-1"><a class="header-anchor" href="#相关概念"><span>相关概念</span></a></h3>
<p>clairvouyant（透视）：当decision-maker接到工作时，它收到的是工作的所有信息：加工时间、工期、权重</p>
<p>non-clairvouyant：当decision-maker接到工作时，它不知道工作信息，只有当工作完成时，它才能知道加工时间</p>
<p>partially-clairvouyant：当decision-maker接到工作时，它知道工作的工期</p>
<p>fully-clairvouyant：当decision-maker接到工作时，知道工作的工期和加工时间</p>
<p>Shortest Remaining Processing Time First：SRPT</p>
<h3 id="内容" tabindex="-1"><a class="header-anchor" href="#内容"><span>内容</span></a></h3>
<p>对于形式为 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>1</mn><mi mathvariant="normal">∣</mi><msub><mi>r</mi><mi>j</mi></msub><mo separator="true">,</mo><mi>p</mi><mi>r</mi><mi>m</mi><mi>p</mi><mi mathvariant="normal">∣</mi><mo>∑</mo><msub><mi>C</mi><mi>j</mi></msub></mrow><annotation encoding="application/x-tex">1|r_j, prmp|\sum C_j</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.0361em;vertical-align:-0.2861em;"></span><span class="mord">1∣</span><span class="mord"><span class="mord mathnormal" style="margin-right:0.02778em;">r</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:-0.0278em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight" style="margin-right:0.05724em;">j</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.2861em;"><span></span></span></span></span></span></span><span class="mpunct">,</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mord mathnormal">p</span><span class="mord mathnormal" style="margin-right:0.02778em;">r</span><span class="mord mathnormal">m</span><span class="mord mathnormal">p</span><span class="mord">∣</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mop op-symbol small-op" style="position:relative;top:0em;">∑</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.07153em;">C</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:-0.0715em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight" style="margin-right:0.05724em;">j</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.2861em;"><span></span></span></span></span></span></span></span></span></span> 的clairvouyant online-over-time 问题，它的可中段SRPT规则的Competitive ratio是1.</p>
<h2 id="theorem-3-7-2" tabindex="-1"><a class="header-anchor" href="#theorem-3-7-2"><span>Theorem 3.7.2</span></a></h2>
<p>对于形式为 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>1</mn><mi mathvariant="normal">∣</mi><msub><mi>r</mi><mi>j</mi></msub><mo separator="true">,</mo><mi>p</mi><mi>r</mi><mi>m</mi><mi>p</mi><mi mathvariant="normal">∣</mi><msub><mi>L</mi><mrow><mi>m</mi><mi>a</mi><mi>x</mi></mrow></msub></mrow><annotation encoding="application/x-tex">1|r_j, prmp|L_{max}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.0361em;vertical-align:-0.2861em;"></span><span class="mord">1∣</span><span class="mord"><span class="mord mathnormal" style="margin-right:0.02778em;">r</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:-0.0278em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight" style="margin-right:0.05724em;">j</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.2861em;"><span></span></span></span></span></span></span><span class="mpunct">,</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mord mathnormal">p</span><span class="mord mathnormal" style="margin-right:0.02778em;">r</span><span class="mord mathnormal">m</span><span class="mord mathnormal">p</span><span class="mord">∣</span><span class="mord"><span class="mord mathnormal">L</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.1514em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight">ma</span><span class="mord mathnormal mtight">x</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span> 的fully-clairvouyant 以及partially-clairvouyant online-over-time 问题，它的可中段EDD规则的Competitive ratio是1.</p>
<h2 id="theorem-3-7-3" tabindex="-1"><a class="header-anchor" href="#theorem-3-7-3"><span>Theorem 3.7.3</span></a></h2>
<h3 id="相关概念-1" tabindex="-1"><a class="header-anchor" href="#相关概念-1"><span>相关概念</span></a></h3>
<p>Round Robin algorithmn (RR算法)</p>
<h3 id="内容-1" tabindex="-1"><a class="header-anchor" href="#内容-1"><span>内容</span></a></h3>
<p>对于形式为 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>1</mn><mi mathvariant="normal">∣</mi><mi>p</mi><mi>r</mi><mi>m</mi><mi>p</mi><mi mathvariant="normal">∣</mi><mo>∑</mo><msub><mi>C</mi><mi>j</mi></msub></mrow><annotation encoding="application/x-tex">1| prmp|\sum C_j</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.0361em;vertical-align:-0.2861em;"></span><span class="mord">1∣</span><span class="mord mathnormal">p</span><span class="mord mathnormal" style="margin-right:0.02778em;">r</span><span class="mord mathnormal">m</span><span class="mord mathnormal">p</span><span class="mord">∣</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mop op-symbol small-op" style="position:relative;top:0em;">∑</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.07153em;">C</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:-0.0715em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight" style="margin-right:0.05724em;">j</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.2861em;"><span></span></span></span></span></span></span></span></span></span> 的non-clairvouyant online-over-time 问题，它的RR算法的Competitive ratio是2.</p>
<h2 id="theorem-3-7-5" tabindex="-1"><a class="header-anchor" href="#theorem-3-7-5"><span>Theorem 3.7.5</span></a></h2>
<p>对于形式为 <span v-pre class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>1</mn><mi mathvariant="normal">∣</mi><mi>p</mi><mi>r</mi><mi>m</mi><mi>p</mi><mi mathvariant="normal">∣</mi><mo>∑</mo><msub><mi>ω</mi><mi>j</mi></msub><msub><mi>C</mi><mi>j</mi></msub></mrow><annotation encoding="application/x-tex">1| prmp|\sum \omega_jC_j</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.0361em;vertical-align:-0.2861em;"></span><span class="mord">1∣</span><span class="mord mathnormal">p</span><span class="mord mathnormal" style="margin-right:0.02778em;">r</span><span class="mord mathnormal">m</span><span class="mord mathnormal">p</span><span class="mord">∣</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mop op-symbol small-op" style="position:relative;top:0em;">∑</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.03588em;">ω</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:-0.0359em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight" style="margin-right:0.05724em;">j</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.2861em;"><span></span></span></span></span></span></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.07153em;">C</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:-0.0715em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight" style="margin-right:0.05724em;">j</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.2861em;"><span></span></span></span></span></span></span></span></span></span> 的partially-clairvouyant online-over-time 问题，它的WRR(Weighted Round Robin)算法的Competitive ratio是2.</p>
</div></template>


