import comp from "D:/projectsvuepress-theme-hope/my-docs/src/.vuepress/.temp/pages/basic_knowledge/Scheduling/Deterministic/Single/online/online.html.vue"
const data = JSON.parse("{\"path\":\"/basic_knowledge/Scheduling/Deterministic/Single/online/online.html\",\"title\":\"Online Scheduling\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Online Scheduling\",\"icon\":\"linter\",\"category\":[\"目录\",\"导航\"],\"tag\":[\"目录\",\"导航\"],\"sticky\":false,\"star\":false,\"article\":false,\"timeline\":false,\"description\":\"概念 不提前知道工作的数量和加工时间(运行时有新任务加入) Theorem 3.7.1 相关概念 clairvouyant（透视）：当decision-maker接到工作时，它收到的是工作的所有信息：加工时间、工期、权重 non-clairvouyant：当decision-maker接到工作时，它不知道工作信息，只有当工作完成时，它才能知道加工时间 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/singingbird-svg/Note/basic_knowledge/Scheduling/Deterministic/Single/online/online.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"文档演示\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Online Scheduling\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"概念 不提前知道工作的数量和加工时间(运行时有新任务加入) Theorem 3.7.1 相关概念 clairvouyant（透视）：当decision-maker接到工作时，它收到的是工作的所有信息：加工时间、工期、权重 non-clairvouyant：当decision-maker接到工作时，它不知道工作信息，只有当工作完成时，它才能知道加工时间 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"singingbird\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"目录\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"导航\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"Online Scheduling\\\",\\\"description\\\":\\\"概念 不提前知道工作的数量和加工时间(运行时有新任务加入) Theorem 3.7.1 相关概念 clairvouyant（透视）：当decision-maker接到工作时，它收到的是工作的所有信息：加工时间、工期、权重 non-clairvouyant：当decision-maker接到工作时，它不知道工作信息，只有当工作完成时，它才能知道加工时间 ...\\\"}\"]]},\"headers\":[{\"level\":2,\"title\":\"概念\",\"slug\":\"概念\",\"link\":\"#概念\",\"children\":[]},{\"level\":2,\"title\":\"Theorem 3.7.1\",\"slug\":\"theorem-3-7-1\",\"link\":\"#theorem-3-7-1\",\"children\":[{\"level\":3,\"title\":\"相关概念\",\"slug\":\"相关概念\",\"link\":\"#相关概念\",\"children\":[]},{\"level\":3,\"title\":\"内容\",\"slug\":\"内容\",\"link\":\"#内容\",\"children\":[]}]},{\"level\":2,\"title\":\"Theorem 3.7.2\",\"slug\":\"theorem-3-7-2\",\"link\":\"#theorem-3-7-2\",\"children\":[]},{\"level\":2,\"title\":\"Theorem 3.7.3\",\"slug\":\"theorem-3-7-3\",\"link\":\"#theorem-3-7-3\",\"children\":[{\"level\":3,\"title\":\"相关概念\",\"slug\":\"相关概念-1\",\"link\":\"#相关概念-1\",\"children\":[]},{\"level\":3,\"title\":\"内容\",\"slug\":\"内容-1\",\"link\":\"#内容-1\",\"children\":[]}]},{\"level\":2,\"title\":\"Theorem 3.7.5\",\"slug\":\"theorem-3-7-5\",\"link\":\"#theorem-3-7-5\",\"children\":[]}],\"readingTime\":{\"minutes\":1.28,\"words\":384},\"filePathRelative\":\"basic_knowledge/Scheduling/Deterministic/Single/online/online.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
