export const themeData = JSON.parse("{\"encrypt\":{\"config\":{\"/demo/encrypt.html\":[\"$2a$10$mIUjzBoJJh2wpFXG28iQU.1081ULEXqYfqeCIv0yTnBHaLPRW9Yei\"]}},\"author\":{\"name\":\"singingbird\",\"url\":\"https://github.com/singingbird-svg\"},\"logo\":\"https://theme-hope-assets.vuejs.press/logo.svg\",\"repo\":\"https://github.com/singingbird-svg\",\"repoLabel\":\"GitHub\",\"repoDisplay\":true,\"docsRepo\":\"https://github.com/singingbird-svg/Note.git\",\"docsBranch\":\"master\",\"docsDir\":\"src\",\"footer\":\"默认页脚\",\"displayFooter\":true,\"locales\":{\"/\":{\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"在 GitHub 上编辑此页\",\"print\":\"打印\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"iconLabel\":\"文章已加密\",\"placeholder\":\"输入密码\",\"remember\":\"记住密码\",\"errorHint\":\"请输入正确的密码\"},\"routeLocales\":{\"skipToContent\":\"跳至主要內容\",\"notFoundTitle\":\"页面不存在\",\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\",\"openInNewWindow\":\"Open in new window\"},\"navbar\":[{\"text\":\"快速导航\",\"icon\":\"navigation\",\"link\":\"/quicknav/\"},{\"text\":\"代码存储\",\"icon\":\"code\",\"link\":\"/codenotes/\"},{\"text\":\"基础知识\",\"icon\":\"note\",\"link\":\"/basic_knowledge/\"},{\"text\":\"论文整理\",\"icon\":\"note\",\"link\":\"/floatinglife/\"},{\"text\":\"资源宝库\",\"icon\":\"advance\",\"prefix\":\"/resources/\",\"children\":[{\"text\":\"书籍资源\",\"icon\":\"animation\",\"link\":\"books/\"},{\"text\":\"论文资源\",\"icon\":\"paper\",\"link\":\"papers/\"},{\"text\":\"视频资源\",\"icon\":\"play\",\"link\":\"videos/\"}]},{\"text\":\"课外杂学\",\"icon\":\"note\",\"link\":\"/others/\"}],\"sidebar\":{\"/codenotes/\":[{\"text\":\"无人机比赛\",\"icon\":\"C++\",\"collapsible\":true,\"link\":\"/codenotes/uav_race/\"}],\"/basic_knowledge/\":[{\"text\":\"基本概念整理\",\"icon\":\"linter\",\"collapsible\":true,\"link\":\"/basic_knowledge/concept/\"},{\"text\":\"深度学习\",\"icon\":\"computer\",\"collapsible\":true,\"link\":\"/basic_knowledge/deeplearning/\"},{\"text\":\"强化学习\",\"icon\":\"strong\",\"collapsible\":true,\"link\":\"/basic_knowledge/rl/\"},{\"text\":\"智能算法\",\"icon\":\"style\",\"collapsible\":true,\"link\":\"/basic_knowledge/smart/\"}],\"/paper/\":[{\"text\":\"自动算法设计\",\"icon\":\"guide\",\"collapsible\":true,\"link\":\"/paper/AAD/\"}],\"/others/\":[{\"text\":\"网络安全\",\"icon\":\"guide\",\"collapsible\":true,\"link\":\"/others/websafe/\"}]}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
